/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the about_us service. Represents a row in the &quot;c_about_us&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.about_usModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.about_usImpl}.
 * </p>
 *
 * @author ganjuss
 * @see about_us
 * @see com.db.model.impl.about_usImpl
 * @see com.db.model.impl.about_usModelImpl
 * @generated
 */
public interface about_usModel extends BaseModel<about_us> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a about_us model instance should use the {@link about_us} interface instead.
	 */

	/**
	 * Returns the primary key of this about_us.
	 *
	 * @return the primary key of this about_us
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this about_us.
	 *
	 * @param primaryKey the primary key of this about_us
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this about_us.
	 *
	 * @return the cid of this about_us
	 */
	public long getCid();

	/**
	 * Sets the cid of this about_us.
	 *
	 * @param cid the cid of this about_us
	 */
	public void setCid(long cid);

	/**
	 * Returns the profile_id of this about_us.
	 *
	 * @return the profile_id of this about_us
	 */
	public long getProfile_id();

	/**
	 * Sets the profile_id of this about_us.
	 *
	 * @param profile_id the profile_id of this about_us
	 */
	public void setProfile_id(long profile_id);

	/**
	 * Returns the text of this about_us.
	 *
	 * @return the text of this about_us
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this about_us.
	 *
	 * @param text the text of this about_us
	 */
	public void setText(String text);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.about_us about_us);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.about_us> toCacheModel();

	@Override
	public com.db.model.about_us toEscapedModel();

	@Override
	public com.db.model.about_us toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}