/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the club_users service. Represents a row in the &quot;c_club_users&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.club_usersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.club_usersImpl}.
 * </p>
 *
 * @author ganjuss
 * @see club_users
 * @see com.db.model.impl.club_usersImpl
 * @see com.db.model.impl.club_usersModelImpl
 * @generated
 */
public interface club_usersModel extends BaseModel<club_users> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a club_users model instance should use the {@link club_users} interface instead.
	 */

	/**
	 * Returns the primary key of this club_users.
	 *
	 * @return the primary key of this club_users
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this club_users.
	 *
	 * @param primaryKey the primary key of this club_users
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this club_users.
	 *
	 * @return the cid of this club_users
	 */
	public long getCid();

	/**
	 * Sets the cid of this club_users.
	 *
	 * @param cid the cid of this club_users
	 */
	public void setCid(long cid);

	/**
	 * Returns the club_id of this club_users.
	 *
	 * @return the club_id of this club_users
	 */
	public long getClub_id();

	/**
	 * Sets the club_id of this club_users.
	 *
	 * @param club_id the club_id of this club_users
	 */
	public void setClub_id(long club_id);

	/**
	 * Returns the user_id of this club_users.
	 *
	 * @return the user_id of this club_users
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this club_users.
	 *
	 * @param user_id the user_id of this club_users
	 */
	public void setUser_id(long user_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.club_users club_users);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.club_users> toCacheModel();

	@Override
	public com.db.model.club_users toEscapedModel();

	@Override
	public com.db.model.club_users toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}