/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the clubs service. Represents a row in the &quot;c_club&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.clubsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.clubsImpl}.
 * </p>
 *
 * @author ganjuss
 * @see clubs
 * @see com.db.model.impl.clubsImpl
 * @see com.db.model.impl.clubsModelImpl
 * @generated
 */
public interface clubsModel extends BaseModel<clubs> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clubs model instance should use the {@link clubs} interface instead.
	 */

	/**
	 * Returns the primary key of this clubs.
	 *
	 * @return the primary key of this clubs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this clubs.
	 *
	 * @param primaryKey the primary key of this clubs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this clubs.
	 *
	 * @return the cid of this clubs
	 */
	public long getCid();

	/**
	 * Sets the cid of this clubs.
	 *
	 * @param cid the cid of this clubs
	 */
	public void setCid(long cid);

	/**
	 * Returns the name of this clubs.
	 *
	 * @return the name of this clubs
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this clubs.
	 *
	 * @param name the name of this clubs
	 */
	public void setName(String name);

	/**
	 * Returns the admin_user_id of this clubs.
	 *
	 * @return the admin_user_id of this clubs
	 */
	public long getAdmin_user_id();

	/**
	 * Sets the admin_user_id of this clubs.
	 *
	 * @param admin_user_id the admin_user_id of this clubs
	 */
	public void setAdmin_user_id(long admin_user_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.clubs clubs);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.clubs> toCacheModel();

	@Override
	public com.db.model.clubs toEscapedModel();

	@Override
	public com.db.model.clubs toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}