/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the hit_count service. Represents a row in the &quot;c_hit_count&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.hit_countModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.hit_countImpl}.
 * </p>
 *
 * @author ganjuss
 * @see hit_count
 * @see com.db.model.impl.hit_countImpl
 * @see com.db.model.impl.hit_countModelImpl
 * @generated
 */
public interface hit_countModel extends BaseModel<hit_count> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hit_count model instance should use the {@link hit_count} interface instead.
	 */

	/**
	 * Returns the primary key of this hit_count.
	 *
	 * @return the primary key of this hit_count
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hit_count.
	 *
	 * @param primaryKey the primary key of this hit_count
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this hit_count.
	 *
	 * @return the cid of this hit_count
	 */
	public long getCid();

	/**
	 * Sets the cid of this hit_count.
	 *
	 * @param cid the cid of this hit_count
	 */
	public void setCid(long cid);

	/**
	 * Returns the profile_id of this hit_count.
	 *
	 * @return the profile_id of this hit_count
	 */
	public long getProfile_id();

	/**
	 * Sets the profile_id of this hit_count.
	 *
	 * @param profile_id the profile_id of this hit_count
	 */
	public void setProfile_id(long profile_id);

	/**
	 * Returns the user_id of this hit_count.
	 *
	 * @return the user_id of this hit_count
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this hit_count.
	 *
	 * @param user_id the user_id of this hit_count
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the counter of this hit_count.
	 *
	 * @return the counter of this hit_count
	 */
	public long getCounter();

	/**
	 * Sets the counter of this hit_count.
	 *
	 * @param counter the counter of this hit_count
	 */
	public void setCounter(long counter);

	/**
	 * Returns the highfive of this hit_count.
	 *
	 * @return the highfive of this hit_count
	 */
	public long getHighfive();

	/**
	 * Sets the highfive of this hit_count.
	 *
	 * @param highfive the highfive of this hit_count
	 */
	public void setHighfive(long highfive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.hit_count hit_count);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.hit_count> toCacheModel();

	@Override
	public com.db.model.hit_count toEscapedModel();

	@Override
	public com.db.model.hit_count toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}