/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the media_links service. Represents a row in the &quot;c_media_links&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.media_linksModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.media_linksImpl}.
 * </p>
 *
 * @author ganjuss
 * @see media_links
 * @see com.db.model.impl.media_linksImpl
 * @see com.db.model.impl.media_linksModelImpl
 * @generated
 */
public interface media_linksModel extends BaseModel<media_links> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a media_links model instance should use the {@link media_links} interface instead.
	 */

	/**
	 * Returns the primary key of this media_links.
	 *
	 * @return the primary key of this media_links
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this media_links.
	 *
	 * @param primaryKey the primary key of this media_links
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this media_links.
	 *
	 * @return the cid of this media_links
	 */
	public long getCid();

	/**
	 * Sets the cid of this media_links.
	 *
	 * @param cid the cid of this media_links
	 */
	public void setCid(long cid);

	/**
	 * Returns the profile_id of this media_links.
	 *
	 * @return the profile_id of this media_links
	 */
	public long getProfile_id();

	/**
	 * Sets the profile_id of this media_links.
	 *
	 * @param profile_id the profile_id of this media_links
	 */
	public void setProfile_id(long profile_id);

	/**
	 * Returns the media_type_id of this media_links.
	 *
	 * @return the media_type_id of this media_links
	 */
	public long getMedia_type_id();

	/**
	 * Sets the media_type_id of this media_links.
	 *
	 * @param media_type_id the media_type_id of this media_links
	 */
	public void setMedia_type_id(long media_type_id);

	/**
	 * Returns the link of this media_links.
	 *
	 * @return the link of this media_links
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this media_links.
	 *
	 * @param link the link of this media_links
	 */
	public void setLink(String link);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.media_links media_links);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.media_links> toCacheModel();

	@Override
	public com.db.model.media_links toEscapedModel();

	@Override
	public com.db.model.media_links toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}