/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the messages service. Represents a row in the &quot;c_messages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.messagesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.messagesImpl}.
 * </p>
 *
 * @author ganjuss
 * @see messages
 * @see com.db.model.impl.messagesImpl
 * @see com.db.model.impl.messagesModelImpl
 * @generated
 */
public interface messagesModel extends BaseModel<messages> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a messages model instance should use the {@link messages} interface instead.
	 */

	/**
	 * Returns the primary key of this messages.
	 *
	 * @return the primary key of this messages
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this messages.
	 *
	 * @param primaryKey the primary key of this messages
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this messages.
	 *
	 * @return the cid of this messages
	 */
	public long getCid();

	/**
	 * Sets the cid of this messages.
	 *
	 * @param cid the cid of this messages
	 */
	public void setCid(long cid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.messages messages);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.messages> toCacheModel();

	@Override
	public com.db.model.messages toEscapedModel();

	@Override
	public com.db.model.messages toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}