/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the profile service. Represents a row in the &quot;c_profile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.profileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.profileImpl}.
 * </p>
 *
 * @author ganjuss
 * @see profile
 * @see com.db.model.impl.profileImpl
 * @see com.db.model.impl.profileModelImpl
 * @generated
 */
public interface profileModel extends BaseModel<profile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile model instance should use the {@link profile} interface instead.
	 */

	/**
	 * Returns the primary key of this profile.
	 *
	 * @return the primary key of this profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile.
	 *
	 * @param primaryKey the primary key of this profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this profile.
	 *
	 * @return the cid of this profile
	 */
	public long getCid();

	/**
	 * Sets the cid of this profile.
	 *
	 * @param cid the cid of this profile
	 */
	public void setCid(long cid);

	/**
	 * Returns the type_id of this profile.
	 *
	 * @return the type_id of this profile
	 */
	public long getType_id();

	/**
	 * Sets the type_id of this profile.
	 *
	 * @param type_id the type_id of this profile
	 */
	public void setType_id(long type_id);

	/**
	 * Returns the genere_id of this profile.
	 *
	 * @return the genere_id of this profile
	 */
	public long getGenere_id();

	/**
	 * Sets the genere_id of this profile.
	 *
	 * @param genere_id the genere_id of this profile
	 */
	public void setGenere_id(long genere_id);

	/**
	 * Returns the user_id of this profile.
	 *
	 * @return the user_id of this profile
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this profile.
	 *
	 * @param user_id the user_id of this profile
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the profile_name of this profile.
	 *
	 * @return the profile_name of this profile
	 */
	@AutoEscape
	public String getProfile_name();

	/**
	 * Sets the profile_name of this profile.
	 *
	 * @param profile_name the profile_name of this profile
	 */
	public void setProfile_name(String profile_name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.profile profile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.profile> toCacheModel();

	@Override
	public com.db.model.profile toEscapedModel();

	@Override
	public com.db.model.profile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}