/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the profile_social_link service. Represents a row in the &quot;c_profile_social_link&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.profile_social_linkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.profile_social_linkImpl}.
 * </p>
 *
 * @author ganjuss
 * @see profile_social_link
 * @see com.db.model.impl.profile_social_linkImpl
 * @see com.db.model.impl.profile_social_linkModelImpl
 * @generated
 */
public interface profile_social_linkModel extends BaseModel<profile_social_link> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile_social_link model instance should use the {@link profile_social_link} interface instead.
	 */

	/**
	 * Returns the primary key of this profile_social_link.
	 *
	 * @return the primary key of this profile_social_link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile_social_link.
	 *
	 * @param primaryKey the primary key of this profile_social_link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this profile_social_link.
	 *
	 * @return the cid of this profile_social_link
	 */
	public long getCid();

	/**
	 * Sets the cid of this profile_social_link.
	 *
	 * @param cid the cid of this profile_social_link
	 */
	public void setCid(long cid);

	/**
	 * Returns the social_type_id of this profile_social_link.
	 *
	 * @return the social_type_id of this profile_social_link
	 */
	public long getSocial_type_id();

	/**
	 * Sets the social_type_id of this profile_social_link.
	 *
	 * @param social_type_id the social_type_id of this profile_social_link
	 */
	public void setSocial_type_id(long social_type_id);

	/**
	 * Returns the link of this profile_social_link.
	 *
	 * @return the link of this profile_social_link
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this profile_social_link.
	 *
	 * @param link the link of this profile_social_link
	 */
	public void setLink(String link);

	/**
	 * Returns the profile_id of this profile_social_link.
	 *
	 * @return the profile_id of this profile_social_link
	 */
	public long getProfile_id();

	/**
	 * Sets the profile_id of this profile_social_link.
	 *
	 * @param profile_id the profile_id of this profile_social_link
	 */
	public void setProfile_id(long profile_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.profile_social_link profile_social_link);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.profile_social_link> toCacheModel();

	@Override
	public com.db.model.profile_social_link toEscapedModel();

	@Override
	public com.db.model.profile_social_link toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}