/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the skill service. Represents a row in the &quot;c_skill&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.db.model.impl.skillModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.db.model.impl.skillImpl}.
 * </p>
 *
 * @author ganjuss
 * @see skill
 * @see com.db.model.impl.skillImpl
 * @see com.db.model.impl.skillModelImpl
 * @generated
 */
public interface skillModel extends BaseModel<skill> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a skill model instance should use the {@link skill} interface instead.
	 */

	/**
	 * Returns the primary key of this skill.
	 *
	 * @return the primary key of this skill
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this skill.
	 *
	 * @param primaryKey the primary key of this skill
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cid of this skill.
	 *
	 * @return the cid of this skill
	 */
	public long getCid();

	/**
	 * Sets the cid of this skill.
	 *
	 * @param cid the cid of this skill
	 */
	public void setCid(long cid);

	/**
	 * Returns the name of this skill.
	 *
	 * @return the name of this skill
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this skill.
	 *
	 * @param name the name of this skill
	 */
	public void setName(String name);

	/**
	 * Returns the genere_id of this skill.
	 *
	 * @return the genere_id of this skill
	 */
	public long getGenere_id();

	/**
	 * Sets the genere_id of this skill.
	 *
	 * @param genere_id the genere_id of this skill
	 */
	public void setGenere_id(long genere_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.db.model.skill skill);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.db.model.skill> toCacheModel();

	@Override
	public com.db.model.skill toEscapedModel();

	@Override
	public com.db.model.skill toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}