/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.acheivements;

import com.db.service.acheivementsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the acheivements service. Represents a row in the &quot;c_acheivments&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link acheivementsImpl}.
 * </p>
 *
 * @author ganjuss
 * @see acheivementsImpl
 * @see com.db.model.acheivements
 * @generated
 */
public abstract class acheivementsBaseImpl extends acheivementsModelImpl
	implements acheivements {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a acheivements model instance should use the {@link acheivements} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			acheivementsLocalServiceUtil.addacheivements(this);
		}
		else {
			acheivementsLocalServiceUtil.updateacheivements(this);
		}
	}
}