/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.club_users;

import com.db.service.club_usersLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the club_users service. Represents a row in the &quot;c_club_users&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link club_usersImpl}.
 * </p>
 *
 * @author ganjuss
 * @see club_usersImpl
 * @see com.db.model.club_users
 * @generated
 */
public abstract class club_usersBaseImpl extends club_usersModelImpl
	implements club_users {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a club_users model instance should use the {@link club_users} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			club_usersLocalServiceUtil.addclub_users(this);
		}
		else {
			club_usersLocalServiceUtil.updateclub_users(this);
		}
	}
}