/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.clubs;
import com.db.model.clubsModel;
import com.db.model.clubsSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the clubs service. Represents a row in the &quot;c_club&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.db.model.clubsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link clubsImpl}.
 * </p>
 *
 * @author ganjuss
 * @see clubsImpl
 * @see com.db.model.clubs
 * @see com.db.model.clubsModel
 * @generated
 */
@JSON(strict = true)
public class clubsModelImpl extends BaseModelImpl<clubs> implements clubsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a clubs model instance should use the {@link com.db.model.clubs} interface instead.
	 */
	public static final String TABLE_NAME = "c_club";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cid", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "admin_user_id", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table c_club (cid LONG not null primary key,name VARCHAR(75) null,admin_user_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table c_club";
	public static final String ORDER_BY_JPQL = " ORDER BY clubs.cid ASC";
	public static final String ORDER_BY_SQL = " ORDER BY c_club.cid ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.db.model.clubs"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.db.model.clubs"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static clubs toModel(clubsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		clubs model = new clubsImpl();

		model.setCid(soapModel.getCid());
		model.setName(soapModel.getName());
		model.setAdmin_user_id(soapModel.getAdmin_user_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<clubs> toModels(clubsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<clubs> models = new ArrayList<clubs>(soapModels.length);

		for (clubsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.db.model.clubs"));

	public clubsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cid;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return clubs.class;
	}

	@Override
	public String getModelClassName() {
		return clubs.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cid", getCid());
		attributes.put("name", getName());
		attributes.put("admin_user_id", getAdmin_user_id());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cid = (Long)attributes.get("cid");

		if (cid != null) {
			setCid(cid);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Long admin_user_id = (Long)attributes.get("admin_user_id");

		if (admin_user_id != null) {
			setAdmin_user_id(admin_user_id);
		}
	}

	@JSON
	@Override
	public long getCid() {
		return _cid;
	}

	@Override
	public void setCid(long cid) {
		_cid = cid;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public long getAdmin_user_id() {
		return _admin_user_id;
	}

	@Override
	public void setAdmin_user_id(long admin_user_id) {
		_admin_user_id = admin_user_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			clubs.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public clubs toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (clubs)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		clubsImpl clubsImpl = new clubsImpl();

		clubsImpl.setCid(getCid());
		clubsImpl.setName(getName());
		clubsImpl.setAdmin_user_id(getAdmin_user_id());

		clubsImpl.resetOriginalValues();

		return clubsImpl;
	}

	@Override
	public int compareTo(clubs clubs) {
		long primaryKey = clubs.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof clubs)) {
			return false;
		}

		clubs clubs = (clubs)obj;

		long primaryKey = clubs.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<clubs> toCacheModel() {
		clubsCacheModel clubsCacheModel = new clubsCacheModel();

		clubsCacheModel.cid = getCid();

		clubsCacheModel.name = getName();

		String name = clubsCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			clubsCacheModel.name = null;
		}

		clubsCacheModel.admin_user_id = getAdmin_user_id();

		return clubsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{cid=");
		sb.append(getCid());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", admin_user_id=");
		sb.append(getAdmin_user_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.db.model.clubs");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cid</column-name><column-value><![CDATA[");
		sb.append(getCid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>admin_user_id</column-name><column-value><![CDATA[");
		sb.append(getAdmin_user_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = clubs.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { clubs.class };
	private long _cid;
	private String _name;
	private long _admin_user_id;
	private clubs _escapedModel;
}