/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.hit_count;
import com.db.model.hit_countModel;
import com.db.model.hit_countSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the hit_count service. Represents a row in the &quot;c_hit_count&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.db.model.hit_countModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hit_countImpl}.
 * </p>
 *
 * @author ganjuss
 * @see hit_countImpl
 * @see com.db.model.hit_count
 * @see com.db.model.hit_countModel
 * @generated
 */
@JSON(strict = true)
public class hit_countModelImpl extends BaseModelImpl<hit_count>
	implements hit_countModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hit_count model instance should use the {@link com.db.model.hit_count} interface instead.
	 */
	public static final String TABLE_NAME = "c_hit_count";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cid", Types.BIGINT },
			{ "profile_id", Types.BIGINT },
			{ "user_id", Types.BIGINT },
			{ "counter", Types.BIGINT },
			{ "highfive", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table c_hit_count (cid LONG not null primary key,profile_id LONG,user_id LONG,counter LONG,highfive LONG)";
	public static final String TABLE_SQL_DROP = "drop table c_hit_count";
	public static final String ORDER_BY_JPQL = " ORDER BY hit_count.cid ASC";
	public static final String ORDER_BY_SQL = " ORDER BY c_hit_count.cid ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.db.model.hit_count"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.db.model.hit_count"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static hit_count toModel(hit_countSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		hit_count model = new hit_countImpl();

		model.setCid(soapModel.getCid());
		model.setProfile_id(soapModel.getProfile_id());
		model.setUser_id(soapModel.getUser_id());
		model.setCounter(soapModel.getCounter());
		model.setHighfive(soapModel.getHighfive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<hit_count> toModels(hit_countSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<hit_count> models = new ArrayList<hit_count>(soapModels.length);

		for (hit_countSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.db.model.hit_count"));

	public hit_countModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cid;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return hit_count.class;
	}

	@Override
	public String getModelClassName() {
		return hit_count.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cid", getCid());
		attributes.put("profile_id", getProfile_id());
		attributes.put("user_id", getUser_id());
		attributes.put("counter", getCounter());
		attributes.put("highfive", getHighfive());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cid = (Long)attributes.get("cid");

		if (cid != null) {
			setCid(cid);
		}

		Long profile_id = (Long)attributes.get("profile_id");

		if (profile_id != null) {
			setProfile_id(profile_id);
		}

		Long user_id = (Long)attributes.get("user_id");

		if (user_id != null) {
			setUser_id(user_id);
		}

		Long counter = (Long)attributes.get("counter");

		if (counter != null) {
			setCounter(counter);
		}

		Long highfive = (Long)attributes.get("highfive");

		if (highfive != null) {
			setHighfive(highfive);
		}
	}

	@JSON
	@Override
	public long getCid() {
		return _cid;
	}

	@Override
	public void setCid(long cid) {
		_cid = cid;
	}

	@JSON
	@Override
	public long getProfile_id() {
		return _profile_id;
	}

	@Override
	public void setProfile_id(long profile_id) {
		_profile_id = profile_id;
	}

	@JSON
	@Override
	public long getUser_id() {
		return _user_id;
	}

	@Override
	public void setUser_id(long user_id) {
		_user_id = user_id;
	}

	@JSON
	@Override
	public long getCounter() {
		return _counter;
	}

	@Override
	public void setCounter(long counter) {
		_counter = counter;
	}

	@JSON
	@Override
	public long getHighfive() {
		return _highfive;
	}

	@Override
	public void setHighfive(long highfive) {
		_highfive = highfive;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			hit_count.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public hit_count toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (hit_count)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		hit_countImpl hit_countImpl = new hit_countImpl();

		hit_countImpl.setCid(getCid());
		hit_countImpl.setProfile_id(getProfile_id());
		hit_countImpl.setUser_id(getUser_id());
		hit_countImpl.setCounter(getCounter());
		hit_countImpl.setHighfive(getHighfive());

		hit_countImpl.resetOriginalValues();

		return hit_countImpl;
	}

	@Override
	public int compareTo(hit_count hit_count) {
		long primaryKey = hit_count.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof hit_count)) {
			return false;
		}

		hit_count hit_count = (hit_count)obj;

		long primaryKey = hit_count.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<hit_count> toCacheModel() {
		hit_countCacheModel hit_countCacheModel = new hit_countCacheModel();

		hit_countCacheModel.cid = getCid();

		hit_countCacheModel.profile_id = getProfile_id();

		hit_countCacheModel.user_id = getUser_id();

		hit_countCacheModel.counter = getCounter();

		hit_countCacheModel.highfive = getHighfive();

		return hit_countCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{cid=");
		sb.append(getCid());
		sb.append(", profile_id=");
		sb.append(getProfile_id());
		sb.append(", user_id=");
		sb.append(getUser_id());
		sb.append(", counter=");
		sb.append(getCounter());
		sb.append(", highfive=");
		sb.append(getHighfive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.db.model.hit_count");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cid</column-name><column-value><![CDATA[");
		sb.append(getCid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>profile_id</column-name><column-value><![CDATA[");
		sb.append(getProfile_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>user_id</column-name><column-value><![CDATA[");
		sb.append(getUser_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>counter</column-name><column-value><![CDATA[");
		sb.append(getCounter());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>highfive</column-name><column-value><![CDATA[");
		sb.append(getHighfive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = hit_count.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			hit_count.class
		};
	private long _cid;
	private long _profile_id;
	private long _user_id;
	private long _counter;
	private long _highfive;
	private hit_count _escapedModel;
}