/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.media_links;

import com.db.service.media_linksLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the media_links service. Represents a row in the &quot;c_media_links&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link media_linksImpl}.
 * </p>
 *
 * @author ganjuss
 * @see media_linksImpl
 * @see com.db.model.media_links
 * @generated
 */
public abstract class media_linksBaseImpl extends media_linksModelImpl
	implements media_links {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a media_links model instance should use the {@link media_links} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			media_linksLocalServiceUtil.addmedia_links(this);
		}
		else {
			media_linksLocalServiceUtil.updatemedia_links(this);
		}
	}
}