/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.messages;

import com.db.service.messagesLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the messages service. Represents a row in the &quot;c_messages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link messagesImpl}.
 * </p>
 *
 * @author ganjuss
 * @see messagesImpl
 * @see com.db.model.messages
 * @generated
 */
public abstract class messagesBaseImpl extends messagesModelImpl
	implements messages {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a messages model instance should use the {@link messages} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			messagesLocalServiceUtil.addmessages(this);
		}
		else {
			messagesLocalServiceUtil.updatemessages(this);
		}
	}
}