/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.skill_user_mapping;

import com.db.service.skill_user_mappingLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the skill_user_mapping service. Represents a row in the &quot;c_skill_user_mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link skill_user_mappingImpl}.
 * </p>
 *
 * @author ganjuss
 * @see skill_user_mappingImpl
 * @see com.db.model.skill_user_mapping
 * @generated
 */
public abstract class skill_user_mappingBaseImpl
	extends skill_user_mappingModelImpl implements skill_user_mapping {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a skill_user_mapping model instance should use the {@link skill_user_mapping} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			skill_user_mappingLocalServiceUtil.addskill_user_mapping(this);
		}
		else {
			skill_user_mappingLocalServiceUtil.updateskill_user_mapping(this);
		}
	}
}