/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.skill_user_mapping;
import com.db.model.skill_user_mappingModel;
import com.db.model.skill_user_mappingSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the skill_user_mapping service. Represents a row in the &quot;c_skill_user_mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.db.model.skill_user_mappingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link skill_user_mappingImpl}.
 * </p>
 *
 * @author ganjuss
 * @see skill_user_mappingImpl
 * @see com.db.model.skill_user_mapping
 * @see com.db.model.skill_user_mappingModel
 * @generated
 */
@JSON(strict = true)
public class skill_user_mappingModelImpl extends BaseModelImpl<skill_user_mapping>
	implements skill_user_mappingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a skill_user_mapping model instance should use the {@link com.db.model.skill_user_mapping} interface instead.
	 */
	public static final String TABLE_NAME = "c_skill_user_mapping";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cid", Types.BIGINT },
			{ "skill_id", Types.BIGINT },
			{ "profile_id", Types.BIGINT },
			{ "type_id", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table c_skill_user_mapping (cid LONG not null primary key,skill_id LONG,profile_id LONG,type_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table c_skill_user_mapping";
	public static final String ORDER_BY_JPQL = " ORDER BY skill_user_mapping.cid ASC";
	public static final String ORDER_BY_SQL = " ORDER BY c_skill_user_mapping.cid ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.db.model.skill_user_mapping"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.db.model.skill_user_mapping"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static skill_user_mapping toModel(skill_user_mappingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		skill_user_mapping model = new skill_user_mappingImpl();

		model.setCid(soapModel.getCid());
		model.setSkill_id(soapModel.getSkill_id());
		model.setProfile_id(soapModel.getProfile_id());
		model.setType_id(soapModel.getType_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<skill_user_mapping> toModels(
		skill_user_mappingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<skill_user_mapping> models = new ArrayList<skill_user_mapping>(soapModels.length);

		for (skill_user_mappingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.db.model.skill_user_mapping"));

	public skill_user_mappingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cid;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return skill_user_mapping.class;
	}

	@Override
	public String getModelClassName() {
		return skill_user_mapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cid", getCid());
		attributes.put("skill_id", getSkill_id());
		attributes.put("profile_id", getProfile_id());
		attributes.put("type_id", getType_id());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cid = (Long)attributes.get("cid");

		if (cid != null) {
			setCid(cid);
		}

		Long skill_id = (Long)attributes.get("skill_id");

		if (skill_id != null) {
			setSkill_id(skill_id);
		}

		Long profile_id = (Long)attributes.get("profile_id");

		if (profile_id != null) {
			setProfile_id(profile_id);
		}

		Long type_id = (Long)attributes.get("type_id");

		if (type_id != null) {
			setType_id(type_id);
		}
	}

	@JSON
	@Override
	public long getCid() {
		return _cid;
	}

	@Override
	public void setCid(long cid) {
		_cid = cid;
	}

	@JSON
	@Override
	public long getSkill_id() {
		return _skill_id;
	}

	@Override
	public void setSkill_id(long skill_id) {
		_skill_id = skill_id;
	}

	@JSON
	@Override
	public long getProfile_id() {
		return _profile_id;
	}

	@Override
	public void setProfile_id(long profile_id) {
		_profile_id = profile_id;
	}

	@JSON
	@Override
	public long getType_id() {
		return _type_id;
	}

	@Override
	public void setType_id(long type_id) {
		_type_id = type_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			skill_user_mapping.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public skill_user_mapping toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (skill_user_mapping)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		skill_user_mappingImpl skill_user_mappingImpl = new skill_user_mappingImpl();

		skill_user_mappingImpl.setCid(getCid());
		skill_user_mappingImpl.setSkill_id(getSkill_id());
		skill_user_mappingImpl.setProfile_id(getProfile_id());
		skill_user_mappingImpl.setType_id(getType_id());

		skill_user_mappingImpl.resetOriginalValues();

		return skill_user_mappingImpl;
	}

	@Override
	public int compareTo(skill_user_mapping skill_user_mapping) {
		long primaryKey = skill_user_mapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof skill_user_mapping)) {
			return false;
		}

		skill_user_mapping skill_user_mapping = (skill_user_mapping)obj;

		long primaryKey = skill_user_mapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<skill_user_mapping> toCacheModel() {
		skill_user_mappingCacheModel skill_user_mappingCacheModel = new skill_user_mappingCacheModel();

		skill_user_mappingCacheModel.cid = getCid();

		skill_user_mappingCacheModel.skill_id = getSkill_id();

		skill_user_mappingCacheModel.profile_id = getProfile_id();

		skill_user_mappingCacheModel.type_id = getType_id();

		return skill_user_mappingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{cid=");
		sb.append(getCid());
		sb.append(", skill_id=");
		sb.append(getSkill_id());
		sb.append(", profile_id=");
		sb.append(getProfile_id());
		sb.append(", type_id=");
		sb.append(getType_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.db.model.skill_user_mapping");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cid</column-name><column-value><![CDATA[");
		sb.append(getCid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>skill_id</column-name><column-value><![CDATA[");
		sb.append(getSkill_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>profile_id</column-name><column-value><![CDATA[");
		sb.append(getProfile_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type_id</column-name><column-value><![CDATA[");
		sb.append(getType_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = skill_user_mapping.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			skill_user_mapping.class
		};
	private long _cid;
	private long _skill_id;
	private long _profile_id;
	private long _type_id;
	private skill_user_mapping _escapedModel;
}