/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.social_login;
import com.db.model.social_loginModel;
import com.db.model.social_loginSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the social_login service. Represents a row in the &quot;c_social_login&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.db.model.social_loginModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link social_loginImpl}.
 * </p>
 *
 * @author ganjuss
 * @see social_loginImpl
 * @see com.db.model.social_login
 * @see com.db.model.social_loginModel
 * @generated
 */
@JSON(strict = true)
public class social_loginModelImpl extends BaseModelImpl<social_login>
	implements social_loginModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a social_login model instance should use the {@link com.db.model.social_login} interface instead.
	 */
	public static final String TABLE_NAME = "c_social_login";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cid", Types.BIGINT },
			{ "social_type_id", Types.BIGINT },
			{ "profile_id", Types.BIGINT },
			{ "social_id", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table c_social_login (cid LONG not null primary key,social_type_id LONG,profile_id LONG,social_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table c_social_login";
	public static final String ORDER_BY_JPQL = " ORDER BY social_login.cid ASC";
	public static final String ORDER_BY_SQL = " ORDER BY c_social_login.cid ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.db.model.social_login"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.db.model.social_login"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static social_login toModel(social_loginSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		social_login model = new social_loginImpl();

		model.setCid(soapModel.getCid());
		model.setSocial_type_id(soapModel.getSocial_type_id());
		model.setProfile_id(soapModel.getProfile_id());
		model.setSocial_id(soapModel.getSocial_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<social_login> toModels(social_loginSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<social_login> models = new ArrayList<social_login>(soapModels.length);

		for (social_loginSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.db.model.social_login"));

	public social_loginModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cid;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return social_login.class;
	}

	@Override
	public String getModelClassName() {
		return social_login.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cid", getCid());
		attributes.put("social_type_id", getSocial_type_id());
		attributes.put("profile_id", getProfile_id());
		attributes.put("social_id", getSocial_id());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cid = (Long)attributes.get("cid");

		if (cid != null) {
			setCid(cid);
		}

		Long social_type_id = (Long)attributes.get("social_type_id");

		if (social_type_id != null) {
			setSocial_type_id(social_type_id);
		}

		Long profile_id = (Long)attributes.get("profile_id");

		if (profile_id != null) {
			setProfile_id(profile_id);
		}

		Long social_id = (Long)attributes.get("social_id");

		if (social_id != null) {
			setSocial_id(social_id);
		}
	}

	@JSON
	@Override
	public long getCid() {
		return _cid;
	}

	@Override
	public void setCid(long cid) {
		_cid = cid;
	}

	@JSON
	@Override
	public long getSocial_type_id() {
		return _social_type_id;
	}

	@Override
	public void setSocial_type_id(long social_type_id) {
		_social_type_id = social_type_id;
	}

	@JSON
	@Override
	public long getProfile_id() {
		return _profile_id;
	}

	@Override
	public void setProfile_id(long profile_id) {
		_profile_id = profile_id;
	}

	@JSON
	@Override
	public long getSocial_id() {
		return _social_id;
	}

	@Override
	public void setSocial_id(long social_id) {
		_social_id = social_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			social_login.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public social_login toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (social_login)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		social_loginImpl social_loginImpl = new social_loginImpl();

		social_loginImpl.setCid(getCid());
		social_loginImpl.setSocial_type_id(getSocial_type_id());
		social_loginImpl.setProfile_id(getProfile_id());
		social_loginImpl.setSocial_id(getSocial_id());

		social_loginImpl.resetOriginalValues();

		return social_loginImpl;
	}

	@Override
	public int compareTo(social_login social_login) {
		long primaryKey = social_login.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof social_login)) {
			return false;
		}

		social_login social_login = (social_login)obj;

		long primaryKey = social_login.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<social_login> toCacheModel() {
		social_loginCacheModel social_loginCacheModel = new social_loginCacheModel();

		social_loginCacheModel.cid = getCid();

		social_loginCacheModel.social_type_id = getSocial_type_id();

		social_loginCacheModel.profile_id = getProfile_id();

		social_loginCacheModel.social_id = getSocial_id();

		return social_loginCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{cid=");
		sb.append(getCid());
		sb.append(", social_type_id=");
		sb.append(getSocial_type_id());
		sb.append(", profile_id=");
		sb.append(getProfile_id());
		sb.append(", social_id=");
		sb.append(getSocial_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.db.model.social_login");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cid</column-name><column-value><![CDATA[");
		sb.append(getCid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>social_type_id</column-name><column-value><![CDATA[");
		sb.append(getSocial_type_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>profile_id</column-name><column-value><![CDATA[");
		sb.append(getProfile_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>social_id</column-name><column-value><![CDATA[");
		sb.append(getSocial_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = social_login.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			social_login.class
		};
	private long _cid;
	private long _social_type_id;
	private long _profile_id;
	private long _social_id;
	private social_login _escapedModel;
}