/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.db.model.impl;

import com.db.model.social_login;

import com.db.service.social_loginLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the social_login service. Represents a row in the &quot;c_social_login&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link social_loginImpl}.
 * </p>
 *
 * @author ganjuss
 * @see social_loginImpl
 * @see com.db.model.social_login
 * @generated
 */
public abstract class social_loginBaseImpl extends social_loginModelImpl
	implements social_login {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a social_login model instance should use the {@link social_login} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			social_loginLocalServiceUtil.addsocial_login(this);
		}
		else {
			social_loginLocalServiceUtil.updatesocial_login(this);
		}
	}
}